site_name: Web Development
markdown_extensions:
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- attr_list
- md_in_html
- footnotes
nav:
- Home: index.md
plugins:
- mkdocstrings
theme:
  name: material
  palette:
  - accent: yellow
    media: 'prefers-color-scheme: dark'
    primary: yellow
    scheme: slate
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - accent: yellow
    media: 'prefers-color-scheme: light'
    primary: yellow
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
watch:
  - "mkdocs.yml"
